[tools]
bun = "latest"
deno = "latest"
node = "lts"
"npm:@vtsls/language-server" = "latest"
pnpm = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:yaml-language-server" = "latest"
"npm:svelte-language-server" = "latest"
